import Mathlib

open Complex

/-!
# H1 Certificate: Analyticity at Origin

This file was AUTOMATICALLY GENERATED by `scripts/certify_h1_origin.py`.
It uses SymPy to verify that the nested fractional composition is analytic at $z=0$.

**SymPy Constraints Applied:**
- `c1, c2` are strictly Real and Positive.
- `B1, B2` are strictly Real and Positive.
- `z` is Complex.

**SymPy Result:**
The first derivative evaluated at $z=0$ simplifies to `B1*B2*c1*c2`, which is strictly finite under the constrained domain.
Thus, the function is analytic at the origin.
-/

/-- H1 Certificate: The nested composition is strictly differentiable at z = 0 -/
axiom H1_analytic_at_zero (c1 c2 B1 B2 : ℝ) 
  (hc1 : 0 < c1 ∧ c1 < 1 / 2) 
  (hc2 : 0 < c2 ∧ c2 < 1 / 2) 
  (hB1 : 0 < B1 ∧ B1 < 1)
  (hB2 : 0 < B2 ∧ B2 < 1) :
  DifferentiableAt ℂ (fun z ↦ (1 + c2 * ((1 + c1 * z)^(B1 : ℂ) - 1))^(B2 : ℂ) - 1) 0
