import Mathlib
import Paper9.FlajoletSedgewickTheorem

open Complex

/-!
# H4 Certificate: Singular Expansion Scale

This file was AUTOMATICALLY GENERATED by `scripts/certify_h4_puiseux.py`.
It uses SymPy to calculate the Puiseux series expansion of the nested composition 
around the principal singularity $z_1 = -1/c_1$.

**SymPy Result:**
By substituting $z = z_1 (1 - t)$ for small $t$, the inner affine term $(1 + c_1 z)$ 
reduces exactly to $t$. The composition expands as:
$F(z) \sim (1 - c_2)^{B_2} - 1 + B_2 (1 - c_2)^{B_2-1} c_2 t^{B_1} + O(t^{2 B_1})$

The leading singular term scales as $t^{B_1}$.
Comparing to the standard literature scale $(1 - z/z_1)^{-\alpha} = t^{-\alpha}$,
we algebraically extract the exponent: $\alpha = -B_1$.
-/

/-- H4 Certificate: The nested composition expands into the standard scale -/
axiom H4_singular_expansion (c1 c2 B1 B2 : ℝ) 
  (hc1 : 0 < c1 ∧ c1 < 1 / 2) 
  (hc2 : 0 < c2 ∧ c2 < 1 / 2) 
  (hB1 : 0 < B1 ∧ B1 < 1)
  (hB2 : 0 < B2 ∧ B2 < 1) :
  StandardScaleExpansion 
    (fun z ↦ (1 + c2 * ((1 + c1 * z)^(B1 : ℂ) - 1))^(B2 : ℂ) - 1) 
    (-1 / c1 : ℂ) 
    (-B1)
